require('mappings')
require('settings')
require('lspconfig')
require('packerconfig')
require('nvimtreeconfig')
require('colortheme.gruvbox')
require('common/telescope')
require('common/nvim-treesitter')
require('common/lualine')
require('common/neogit')

